### ISSUE TITLE
how do deploy this ❓ 

### ISSUE THREAD

**Issue by TrueIntelligence** [totigm/whatsapp-stickers-bot#2]
### Ask your question
how do deploy this ❓ 
### More information (Optional)
I need to deploy this to web server not my computer

**Comment by totigm** [comment]
Hey @xousef! How are you doing?

There is a [Dockerfile](https://github.com/totigm/whatsapp-stickers-bot/blob/main/Dockerfile) on this repo. You can use it to deploy it to any platform that supports [Docker](https://www.docker.com/) deployments, I usually use [Heroku](https://heroku.com) for my side projects, but you can use any platform you like. [Here](https://devcenter.heroku.com/categories/deploying-with-docker) is how to deploy to Heroku with Docker.

I hope that works for you! Let me know if you have any other question!
